### ISSUE TITLE
拼音转换有误

### ISSUE THREAD

**Issue by Yeyangshu** [houbb/pinyin#14]
很感谢您提供了这么好的框架，但是我在生僻字测试的时候发现有个别汉字转换后的拼音有误，比如：叁（sān），转换后的拼音为：cān，希望您看到可以优化一下。

**Comment by houbb** [comment]
感谢提醒，有时间我确认下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yeyangshu ***@***.***&gt;
发送时间: 2021年9月30日 17:43
收件人: houbb/pinyin ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[houbb/pinyin] 拼音转换有误 (#14)





 
很感谢您提供了这么好的框架，但是我在生僻字测试的时候发现有个别汉字转换后的拼音有误，比如：叁（sān），转换后的拼音为：cān，希望您看到可以优化一下。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houbb** [comment]
v0.2.2 已修复。
